version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: on-failure:5
    ports:
      - "2181:2181"
  broker:
    image: wurstmeister/kafka:2.13-2.6.0
    restart: on-failure:5
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "events:1:1"
    volumes:
      - kafka-data:/var/run/docker.sock

  postgres_db:
    image: postgres:12
    restart: on-failure:5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  adminer:
      image: adminer
      restart: always
      ports:
        - 8081:8080

volumes:
  kafka-data:
  postgres-data:
